@echo off
echo Starting setup...
if not exist public mkdir public
if not exist public\frames mkdir public\frames
echo Copying frames...
xcopy assets\frames\* public\frames\ /s /e /y /i
echo Installing dependencies...
call npm install
echo Building...
call npm run build
echo Setup complete.
